name: EgoriaMC
version: 1.0
main: me.egoriamc.EgoriaMC
api-version: 1.13
authors:
  - egoriamc
description: Plugin de gestion des homes et messages personnalisés

commands:
  help:
    description: Affiche l'aide du plugin
    usage: /help
    permission: egoriamc.help
  home:
    description: Permet de gérer vos homes
    usage: /home [set|delete|list|gui|tp|staffhomes <name>]
    permission: egoriamc.home.use
  warp:
    description: Permet de gérer les warps
    usage: /warp [set|delete|list|info <name>|<name>]
    permission: egoriamc.warp.use
  plugins:
    description: Affiche la liste des plugins
    usage: /plugins
    permission: egoriamc.plugins
  annonce:
    description: Envoie une annonce à tous les joueurs
    usage: /annonce <message>
    permission: egoriamc.announce
    aliases: [announce, broadcast]
  furnace:
    description: Cuit automatiquement l'item dans la main du joueur (grade Gardien)
    usage: /furnace
    permission: egoriamc.furnace.use
  craft:
    description: Ouvre une table de craft (grade Gardien)
    usage: /craft
    permission: egoriamc.craft.use
  live:
    description: Annonce un live (grade Streamer)
    usage: /live <URL>
    permission: egoriamc.live.use
  reload:
    description: Recharge la configuration du plugin
    usage: /reload
    permission: egoriamc.reload
  warn:
    description: Donne un avertissement à un joueur (enregistré en BDD)
    usage: /warn <pseudo> <raison>
    permission: egoriamc.warn

permissions:
  egoriamc.help:
    description: Permet de voir l'aide du plugin
    default: true
  egoriamc.plugins:
    description: Permet de voir la liste des plugins
    default: true
  egoriamc.home.use:
    description: Permet d'utiliser les homes
    default: true
  egoriamc.home.admin:
    description: Permet de gérer les homes d'autres joueurs
    default: op
  egoriamc.home.staff:
    description: Permet de voir les homes des joueurs (Staff)
    default: op
  egoriamc.warp.use:
    description: Permet de se téléporter aux warps
    default: true
  egoriamc.warp.admin:
    description: Permet de créer/supprimer des warps
    default: op
  egoriamc.announce:
    description: Permet d'envoyer des annonces à tous les joueurs
    default: op
  egoriamc.furnace.use:
    description: Permet de cuire automatiquement les items (grade Gardien)
    default: op
  egoriamc.craft.use:
    description: Permet d'ouvrir une table de craft (grade Gardien)
    default: op
  egoriamc.live.use:
    description: Permet de faire des annonces de live (grade Streamer)
    default: op
  egoriamc.reload:
    description: Permet de recharger la configuration du plugin
    default: op
  egoriamc.warn:
    description: Permet d'avertir un joueur (warn en BDD)
    default: op
